In [ ]:
import pandas as pd

In [ ]:
testData = {
    'name' : ['Somesh','Samit','Ninad', 'Prasad', 'Om'],
    'height' : [6.3, 6.2, 5.2, 5.4, 5.8]
}

In [ ]:
df = pd.DataFrame(testData)

In [ ]:
df

     name  height
0  Somesh     6.3
1   Samit     6.2
2   Ninad     5.2
3  Prasad     5.4
4      Om     5.8

In [ ]:
# these outliers are on the higher end
max_threshold = df['height'].quantile(0.95)
max_threshold

6.28

In [ ]:
 df[df['height'] > max_threshold]

     name  height
0  Somesh     6.3

In [ ]:
# these outliers are on the lower end 
min_threshold = df['height'].quantile(0.05)
min_threshold

5.24

In [ ]:
df[df['height'] < min_threshold]

    name  height
2  Ninad     5.2

In [ ]:
# we can do the above mentioned in one go itself 
df2 = df[(df['height'] < max_threshold) & (df['height'] > min_threshold)]
df2 # now df2 has almost no outliers remaining!

     name  height
1   Samit     6.2
3  Prasad     5.4
4      Om     5.8